### ISSUE TITLE
webview中跳转路由，不能手势操作返回

### ISSUE THREAD

**Issue by iamstd** [Fitem/native_bridge#1]
Fitem：
   你好，打开webview后，使用vue框架，多次跳转前端路由，手势操作返回时，直接退出了webview。这一问题，你是否有遇到？期待你的回复。谢谢。

**Comment by Fitem** [comment]
在Flutter中，iOS页面的手势返回和 WebView 中网页的手势返回冲突问题。可以给WebView所在页面添加WillPopScope拦截为null，确保WebView返回生效，或者禁用WebView的手势返回仅点击网页标题栏的返回按钮返回。若想要和Android一样支持WebView + Page 返回效果，则需要修改WebView组件的源码才可以。

**Comment by Fitem** [comment]
> 

在Flutter中，iOS页面的手势返回和 WebView 中网页的手势返回冲突问题。可以给WebView所在页面添加WillPopScope拦截为null，确保WebView返回生效，或者禁用WebView的手势返回仅点击网页标题栏的返回按钮返回。若想要和Android一样支持WebView + Page 返回效果，则需要修改WebView组件的源码才可以。

**Comment by Fitem** [comment]
> Fitem： 你好，打开webview后，使用vue框架，多次跳转前端路由，手势操作返回时，直接退出了webview。这一问题，你是否有遇到？期待你的回复。谢谢。

在Flutter中，iOS页面的手势返回和 WebView 中网页的手势返回冲突问题。可以给WebView所在页面添加WillPopScope拦截为null，确保WebView返回生效，或者禁用WebView的手势返回仅点击网页标题栏的返回按钮返回。若想要和Android一样支持WebView + Page 返回效果，则需要修改WebView组件的源码才可以。

目前市面上大部分的App都是：禁用 WebView所在页面的手势返回，或者禁用WebView的手势返回，两种方式。
